export const colors = [
  [108,148,52],/*Abies alba*/
  [77,153,113],/*Acer campestre*/
  [175,238,144],/*Acer negundo*/
  [94,186,79],/*Acer platanoides*/
  [67,115,89],/*Acer pseudoplatanus*/
  [77,113,43],/*Ailanthus altissima*/
  [134,174,48],/*Alnus alnobetula*/
  [73,107,57],/*Alnus glutinosa*/
  [182,216,81],/*Alnus incana*/
  [68,114,15],/*Betula pendula*/
  [154,187,44],/*Betula pubescens*/
  [156,214,54],/*Carpinus betulus*/
  [157,206,52],/*Castanea sativa*/
  [226,187,0],/*Cornus mas*/
  [236,73,53],/*Cornus sanguinea*/
  [166,208,531],/*Corylus avellana*/
  [247,252,246],/*Crataegus monogyna*/
  [255,123,201],/*Euonymus europaeus*/
  [255,172,180],/*Euonymus verrucosus*/
  [133,149,24],/*Fagus sylvatica*/
  [33,102,45],/*Frangula alnus*/
  [124,160,112],/*Fraxinus angustifolia*/
  [],/*Fraxinus excelsior*/
  [],/*Fraxinus ornus*/
  [],/*Ilex aquifolium*/
  [],/*Juglans nigra*/
  [],/*Juglans regia*/
  [],/*Juniperus communis*/
  [],/*Larix decidua*/
  [],/*Ligustrum vulgare*/
  [],/*Picea abies*/
  [],/*Pinus cembra*/
  [],/*Pinus mugo*/
  [],/*Pinus nigra*/
  [],/*Pinus strobus*/
  [],/*Pinus sylvestris*/
  [],/*Populus alba*/
  [],/*Populus canescens*/
  [],/*Populus nigra*/
  [],/*Populus tremula*/
  [],/*Prunus avium*/
  [],/*Prunus padus*/
  [],/*Prunus spinosa*/
  [],/*Pseudotsuga menziesii*/
  [],/*Pyrus pyraster*/
  [],/*Quercus cerris*/
  [],/*Quercus petraea*/
  [],/*Quercus pubescens*/
  [],/*Quercus robur*/
  [],/*Quercus rubra*/
  [],/*Rhamnus cathartica*/
  [],/*Robinia pseudoacacia*/
  [],/*Salix alba*/
  [],/*Salix caprea*/
  [],/*Salix fragilis*/
  [],/*Salix purpurea*/
  [],/*Sorbus aria*/
  [],/*Sorbus aucuparia*/
  [],/*Sorbus chamaemespilus*/
  [],/*Sorbus torminalis*/
  [],/*Taxus baccata*/
  [],/*Tilia cordata*/
  [],/*Tilia platyphyllos*/
  [],/*Ulmus glabra*/
  [],/*Ulmus laevis*/
  [],/*Ulmus minor*/
  [],/*Prunus serotina*/
  [],/*Ostrya carpinifolia*/
  [],/*Pinus halepensis*/
  [],/*Quercus ilex*/
  [],/*Arbutus andrachne*/
  [],/*Cedrus libani*/
  [],/*Crataegus azarolus*/
  [],/*Olea europaea*/
  [],/*Pinus brutia*/
  [],/*Pistacia lentiscus*/
  [],/*Pistacia terebinthus*/
  [],/*Quercus alnifolia*/
  [],/*Quercus coccifera*/
  [],/*Rhamnus alaternus*/
  [],/*Abies grandis*/
  [],/*Abies procera*/
  [],/*Aesculus hippocastanum*/
  [],/*Cotoneaster integerrimus*/
  [],/*Crataegus laevigata*/
  [],/*Malus sylvestris*/
  [],/*Picea engelmannii*/
  [],/*Picea glauca*/
  [],/*Picea omorika*/
  [],/*Picea pungens*/
  [],/*Pinus banksiana*/
  [],/*Pinus contorta*/
  [],/*Platanus acerifolia*/
  [],/*Prunus domestica*/
  [],/*Pyrus communis*/
  [],/*Quercus palustris*/
  [],/*Salix aurita*/
  [],/*Salix cinerea*/
  [],/*Abies nordmanniana*/
  [],/*Carpinus orientalis*/
  [],/*Cupressus sempervirens*/
  [],/*Larix kaempferi*/
  [],/*Malus domestica*/
  [],/*Picea sitchensis*/
  [],/*Prunus cerasifera*/
  [],/*Sorbus intermedia*/
  [],/*Betula nana*/
  [],/*Cornus suecica*/
  [],/*Larix sibirica*/
  [],/*Salix glauca*/
  [],/*Salix hastata*/
  [],/*Salix lanata*/
  [],/*Salix lapponum*/
  [],/*Salix myrsinifolia*/
  [],/*Salix myrtilloides*/
  [],/*Salix pentandra*/
  [],/*Salix phylicifolia*/
  [],/*Salix repens*/
  [],/*Salix rosmarinifolia*/
  [],/*Salix starkeana*/
  [],/*Abies cephalonica*/
  [],/*Acer monspessulanum*/
  [],/*Acer opalus*/
  [],/*Alnus cordata*/
  [],/*Arbutus unedo*/
  [],/*Buxus sempervirens*/
  [],/*Cedrus atlantica*/
  [],/*Celtis australis*/
  [],/*Cercis siliquastrum*/
  [],/*Chamaecyparis lawsoniana*/
  [],/*Cupressus macrocarpa*/
  [],/*Erica arborea*/
  [],/*Erica scoparia*/
  [],/*Ficus carica*/
  [],/*Juniperus oxycedrus*/
  [],/*Juniperus phoenicea*/
  [],/*Juniperus thurifera*/
  [],/*Laburnum alpinum*/
  [],/*Laburnum anagyroides*/
  [],/*Laurus nobilis*/
  [],/*Liriodendron tulipifera*/
  [],/*Mespilus germanica*/
  [],/*Morus alba*/
  [],/*Phillyrea angustifolia*/
  [],/*Phillyrea latifolia*/
  [],/*Pinus pinaster*/
  [],/*Pinus pinea*/
  [],/*Pinus radiata*/
  [],/*Pistacia atlantica*/
  [],/*Prunus brigantina*/
  [],/*Prunus cerasus*/
  [],/*Prunus dulcis*/
  [],/*Prunus mahaleb*/
  [],/*Pyrus amygdaliformis*/
  [],/*Quercus pyrenaica*/
  [],/*Quercus suber*/
  [],/*Rhamnus alpina*/
  [],/*Rhamnus saxatilis*/
  [],/*Salix atrocinerea*/
  [],/*Salix daphnoides*/
  [],/*Salix eleagnos*/
  [],/*Salix viminalis*/
  [],/*Sambucus nigra*/
  [],/*Sorbus domestica*/
  [],/*Sorbus latifolia*/
  [],/*Sorbus mougeotii*/
  [],/*Tamarix africana*/
  [],/*Tamarix canariensis*/
  [],/*Thuja plicata*/
  [],/*Tsuga heterophylla*/
  [],/*Vachellia farnesiana*/
  [],/*Crataegus crus-galli*/
  [],/*Fraxinus pennsylvanica*/
  [],/*Maclura pomifera*/
  [],/*Pinus ponderosa*/
  [],/*Prunus virginiana*/
  [],/*Salix appendiculata*/
  [],/*Ulmus canescens*/
  [],/*Acer saccharinum*/
  [],/*Acer tataricum*/
  [],/*Juniperus virginiana*/
  [],/*Salix salviifolia*/
  [],/*Styphnolobium japonicum*/
  [],/*Tilia tomentosa*/
  [],/*Acer cappadocicum*/
  [],/*Ceratonia siliqua*/
  [],/*Cupressus arizonica*/
  [],/*Eucalyptus camaldulensis*/
  [],/*Eucalyptus globulus*/
  [],/*Euonymus latifolius*/
  [],/*Paliurus spina-christi*/
  [],/*Paulownia tomentosa*/
  [],/*Pinus heldreichii*/
  [],/*Pinus wallichiana*/
  [],/*Platanus orientalis*/
  [],/*Quercus congesta*/
  [],/*Quercus dalechampii*/
  [],/*Quercus frainetto*/
  [],/*Quercus ithaburensis*/
  [],/*Quercus trojana*/
  [],/*Salix foetida*/
  [],/*Salix glabra*/
  [],/*Prunus persica*/
  [],/*Salix silesiaca*/
  [],/*Quercus faginea*/
  [],/*Abies pinsapo*/
  [],/*Amelanchier ovalis*/
  [],/*Betula humilis*/
  [],/*Elaeagnus rhamnoides*/
  [],/*Fraxinus pallisae*/
  [],/*Juglans cinerea*/
  [],/*Morus nigra*/
  [],/*Prunus armeniaca*/
  [],/*Rhus typhina*/
  [],/*Sambucus racemosa*/
  [],/*Viburnum opulus*/
  [],/*Populus balsamifera*/
  [],/*Frangula rupestris*/
  [],/*Sorbus graeca*/
  [],/*Acacia dealbata*/
  [],/*Acacia melanoxylon*/
  [],/*Cedrus deodara*/
  [],/*Chamaerops humilis*/
  [],/*Crataegus laciniata*/
  [],/*Cupressus lusitanica*/
  [],/*Eucalyptus gomphocephala*/
  [],/*Ilex canariensis*/
  [],/*Juniperus sabina*/
  [],/*Laurus azorica*/
  [],/*Myrica faya*/
  [],/*Myrtus communis*/
  [],/*Persea indica*/
  [],/*Phoenix canariensis*/
  [],/*Picconia excelsa*/
  [],/*Pinus canariensis*/
  [],/*Prunus lusitanica*/
  [],/*Quercus canariensis*/
  [],/*Rhamnus lycioides*/
  [],/*Rhus coriaria*/
  [],/*Salix babylonica*/
  [],/*Salix bicolor*/
  [],/*Tetraclinis articulat*/
];